steps:
- name: node:14.17.3
  entrypoint: npm
  args: ["install"]
  dir: 'back-end'
  env:
    - 'ADMIN_ACC_TYPE=${_ADMIN_ACC_TYPE}'
    - 'ADMIN_AUTH_PROVIDER_CERTL_URL=${_ADMIN_AUTH_PROVIDER_CERTL_URL}'
    - 'ADMIN_AUTH_URI=${_ADMIN_AUTH_URI}'
    - 'ADMIN_CLIENT_CERT_URL=${_ADMIN_CLIENT_CERT_URL}'
    - 'ADMIN_CLIENT_EMAIL=${_ADMIN_CLIENT_EMAIL}'
    - 'ADMIN_CLIENT_ID=${_ADMIN_CLIENT_ID}'
    - 'ADMIN_PRIVATE_KEY=${_ADMIN_PRIVATE_KEY}'
    - 'ADMIN_PRIVATE_KEY_ID=${_ADMIN_PRIVATE_KEY_ID}'
    - 'ADMIN_TOKEN_URI=${_ADMIN_TOKEN_URI}'
    - 'AIR_TABLE_API=${_AIR_TABLE_API}'
    - 'NODE_APP_API_KEY=${_NODE_APP_API_KEY}'
    - 'NODE_APP_AUTH_DOMAIN=${_NODE_APP_AUTH_DOMAIN}'
    - 'NODE_APP_PROJECT_ID=${_NODE_APP_PROJECT_ID}'
    - 'NODE_APP_STORAGE_BUCKET=${_NODE_APP_STORAGE_BUCKET}'
    - 'NODE_APP_MESSAGING_SENDER_ID=${_NODE_APP_MESSAGING_SENDER_ID}'
    - 'NODE_APP_APP_ID=${_NODE_APP_APP_ID}'
    - 'NODE_APP_MEAUSERMENT_ID=${_NODE_APP_MEAUSERMENT_ID}'
    - 'PORT=2000'

- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
  dir: 'back-end'
timeout: "1600s"